# Set up for Petrichor
cores: 64
processes: 64
name: 'spice-worker'
memory: "512GB"
account: 'OD-217087'
#queue: 'workq'
walltime: '0-12:00:00'
job_extra_directives: ['--qos express']
# interface for the workers
interface: "ib0"
log_directory: 'spice_logs'
job_script_prologue: [
    'module load singularity',
]
# job_script_prologue: [
#     'export OMP_NUM_THREADS=1',
#     'source /home/$(whoami)/.bashrc',
#     'conda activate spice'
# ]
# python: 'srun -n 1 -c 64 python'
#worker_extra_args: [
#    "--lifetime", "23h",
#    "--lifetime-stagger", "5m",
#]
death_timeout: 1000
local_directory: $LOCALDIR
