name: spice
channels:
- astropy
- conda-forge
- defaults
- pkgw-forge
dependencies:
- python=3.8
- pip
- future
- numpy
- scipy
- matplotlib
- setuptools
- ipython
- astropy>=4.3
- dask
- dask-jobqueue
- distributed
- prefect
- python-graphviz
- bokeh
- pymongo
- mongodb
- fitsio
- casacore
- casa-data
- pip:
  - tqdm
  - configargparse
  - spectral_cube
  - RM-Tools
  - RMextract
  - spython
  - mpi4py
  - dask_mpi
  - git+https://github.com/CIRADA-Tools/FRion.git
  - pytest
  - RMTable
  - -rrequirements.txt