name: spice
channels:
- astropy
- conda-forge
- defaults
dependencies:
- python=3.8
- pip
- future
- numpy
- scipy
- matplotlib
- setuptools
- ipython
- astropy
- dask
- dask-jobqueue
- distributed
- prefect
- python-graphviz
- bokeh
- pymongo
- mongodb
- dask_mpi
- fitsio
- casacore
- pip:
  - tqdm
  - configargparse
  - spectral_cube
  - RM-Tools
  - RMextract
  - git+https://github.com/CIRADA-Tools/FRion.git
  - -rrequirements.txt