name: arrakis2
channels:
- astropy
- conda-forge
- defaults
- pkgw-forge
dependencies:
- python=3.8
- pip
- future
- numpy
- scipy
- pandas
- matplotlib
- setuptools
- ipython
- astropy>=4.3
- dask
- dask-jobqueue
- distributed
- prefect
- python-graphviz
- bokeh
- pymongo
- mongodb
- fitsio
- casacore
- casa-data
- sphinx
- numpydoc
- sphinx-autoapi
- m2r2
- gfortran
- numba
- pip:
  - ./
