[tool.poetry]
name = "spiceracs"
version = "0.1.0"
description = "Processing polarized RACS data products."
authors = ["Alec Thomson"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.8"
rm-tools = {git = "https://github.com/AlecThomson/RM-Tools.git@spiceracs_dev"}
astropy = "^4.3"
bilby = "*"
casatasks = "*"
ConfigArgParse = "*"
dask = "*"
distributed = "*"
dask_jobqueue = "*"
dask_mpi = "*"
FRion = "*"
h5py = "*"
ipython = "*"
matplotlib = "*"
numba = "*"
numba_progress = "*"
mpi4py = "*"
pandas = "*"
Polspectra = "*"
psutil = "*"
pymongo = "*"
pymultinest = "*"
pytest = "*"
python_casacore = "*"
RACS_tools = "*"
radio_beam = "*"
RMextract = "*"
schwimmbad = "*"
scipy = "*"
sphinx = "*"
spectral_cube = "*"
spython = "*"
tqdm = "*"
vorbin = "*"
graphviz = "*"
bokeh = "*"
numpydoc = "*"
sphinx-autoapi = "*"
m2r2 = "*"
prefect = "<2"
RMTable = { git = "https://github.com/CIRADA-Tools/RMTable" }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
spice_init = "spiceracs.init_database:cli"
spice_process = "spiceracs.process_spice:cli"
spice_region = "spiceracs.process_region:cli"
spice_cat = "spiceracs.makecat:cli"