[tool.poetry]
name = "spiceracs"
version = "0.1.0"
description = "Processing polarized RACS data products."
homepage = "https://research.csiro.au/racs/"
repository = "https://github.com/AlecThomson/spiceracs"
documentation = "https://spiceracs.readthedocs.io/en/latest/"
authors = ["Alec Thomson"]
license = "BSD-3-Clause"
readme = "README.md"
classifiers=[
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Development Status :: 3 - Alpha",
]
packages = [
    { include = "spiceracs"},
]

include = [
    {path='spiceracs/askap_surveys/**/**/*', format=['sdist','wheel']},
    {path='spiceracs/configs/*', format=['sdist','wheel']},
]

[tool.poetry.dependencies]
python = "^3.8"
rm-tools = {git = "https://github.com/AlecThomson/RM-Tools.git@spiceracs_dev"}
astropy = "^5"
bilby = "*"
casatasks = "*"
ConfigArgParse = "*"
dask = "*"
distributed = "*"
dask_jobqueue = "*"
dask_mpi = "*"
FRion = "*"
h5py = "*"
ipython = "*"
matplotlib = "*"
numba = "*"
numba_progress = "*"
mpi4py = "*"
pandas = "*"
Polspectra = "*"
psutil = "*"
pymongo = "*"
pymultinest = "*"
pytest = "*"
python_casacore = "*"
RACS_tools = "*"
radio_beam = "*"
RMextract = "*"
schwimmbad = "*"
scipy = "*"
spectral_cube = "*"
spython = "*"
tqdm = "*"
vorbin = "*"
graphviz = "*"
bokeh = "*"
prefect = "<2"
RMTable = { git = "https://github.com/CIRADA-Tools/RMTable" }
setuptools = "*"

[tool.poetry.dev-dependencies]
black = "^22.10"
flake8 = "^5"
isort = "^5"

[tool.poetry.extras]
docs = [
    "sphinx",
    "sphinx_rtd_theme",
    "sphinx-book-theme",
    "sphinx-autoapi",
    "m2r2",
    "numpydoc",
]

dev = [
    "black>=22.10",
    "flake8>=5",
    "isort>=5",
]

[build-system]
requires = ["poetry-core>=1.2"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
spice_init = "spiceracs.init_database:cli"
spice_process = "spiceracs.process_spice:cli"
spice_region = "spiceracs.process_region:cli"
spice_cat = "spiceracs.makecat:cli"
# Unified script script
casda_prepare = { reference="scripts/casda_prepare.py", type="file"}
check_cutout = { reference="scripts/check_cutout.py", type="file"}
compare_leakage = { reference="scripts/compare_leakage.py", type="file"}
compute_leakage = { reference="scripts/compute_leakage.py", type="file"}
copy_cutouts_askap = { reference="scripts/copy_cutouts_askap.py", type="file"}
copy_cutouts = { reference="scripts/copy_cutouts.py", type="file"}
copy_data = { reference="scripts/copy_data.py", type="file"}
find_row = { reference="scripts/find_row.py", type="file"}
find_sbid = { reference="scripts/find_sbid.py", type="file"}
fix_dr1_cat = { reference="scripts/fix_dr1_cat.py", type="file"}
helloworld = { reference="scripts/helloworld.py", type="file"}
make_links = { reference="scripts/make_links.py", type="file"}
spica = { reference="scripts/spica.py", type="file"}

[tool.isort]
profile = "black"