# Set up for Petrichor
cluster_class: "dask_jobqueue.SLURMCluster"
cluster_kwargs:
    cores: 8
    processes: 8
    name: 'spice-worker'
    memory: "64GiB"
    account: 'OD-217087'
    #queue: 'workq'
    walltime: '0-01:00:00'
    job_extra_directives: ['--qos express']
    # interface for the workers
    interface: "ib0"
    log_directory: 'spice_logs'
    job_script_prologue: [
        'module load singularity',
        'unset SINGULARITY_BINDPATH'
    ]
    local_directory: $LOCALDIR
    silence_logs: 'info'
adapt_kwargs:
    minimum: 1
    maximum: 36
    wait_count: 20
    target_duration: "300s"
    interval: "30s"
