# Set up for Petrichor
cluster_class: "dask_jobqueue.SLURMCluster"
cluster_kwargs:
    cores: 16
    processes: 1
    name: 'spice-worker'
    memory: "128GiB"
    account: 'OD-217087'
    #queue: 'workq'
    walltime: '1-00:00:00'
    job_extra_directives: ['--qos express']
    # interface for the workers
    interface: "ib0"
    log_directory: 'spice_logs'
    job_script_prologue: [
        'module load singularity',
        'unset SINGULARITY_BINDPATH'
    ]
    local_directory: $LOCALDIR
    silence_logs: 'info'
adapt_kwargs:
    minimum_jobs: 1
    maximum_jobs: 36
    wait_count: 20
    target_duration: "300s"
    interval: "30s"
