# Set up for Petrichor
cluster_class: "dask_jobqueue.SLURMCluster"
cluster_kwargs:
    cores: 4
    processes: 4
    name: 'spice-worker'
    memory: "256GiB"
    account: 'OD-217087'
    walltime: '0-01:00:00'
    job_extra_directives: ['--qos express']
    # interface for the workers
    interface: "ib0"
    log_directory: 'spice_logs'
    job_script_prologue: [
        'module load singularity',
        'unset SINGULARITY_BINDPATH',
        'export OMP_NUM_THREADS=1'
    ]
    local_directory: $LOCALDIR
    silence_logs: 'info'
adapt_kwargs:
    minimum_jobs: 1
    maximum_jobs: 128
    wait_count: 20
    target_duration: "5s"
    interval: "10s"
