# Set up for Galaxy
cores: 20
processes: 20
name: 'spice-worker'
memory: "60GB"
project: 'askaprt'
queue: 'workq'
walltime: '12:00:00'
job_extra: ['-M galaxy']
# interface for the workers
interface: "ipogif0"
log_directory: 'spice_logs'
env_extra: [
    # 'export OMP_NUM_THREADS=1',
    'module unload askapsoft',
    'module load askapsoft/1.1.0',
    'unset PYTHONPATH',
    'source /home/$(whoami)/.bashrc',
    'conda activate spice'
]
python: 'srun -n 1 -c 20 python'
extra: [
    "--lifetime", "11h",
    "--lifetime-stagger", "5m",
]
death_timeout: 300
local_directory: '/dev/shm'
